Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Exclude:
    - spec/factories.rb
